### PR TITLE
Throughput config file

### PR DESCRIPTION
**Pull request by daldoyle**
Added config file support for iperf3, allows specifying of path to iperf3 and what port the server should boot up on.

### CODE REVIEW

**Comment by mfeit-internet2** [comment]
For historical context, what was the original purpose of having a configurable pointer to an alternate iperf binary?  Is it something we really need, or are we inviting people to kludge in their own versions and introduce incompatibilities with the established code?

If people want to put alternate versions of tools on their systems, they can be as separate plugins, given different names and given a higher preference so pairs of participants that have it will use it.

Not saying we shouldn't merge this, but this seems like a holdover from the bad old days.

**Comment by daldoyle** [comment]
There actually was no historical precedent for setting the path to iperf3 that I’m aware of - I don’t believe you could configure it under bwctl. I modeled this after the owping configuration to keep things consistent. The “port” specification is needed, but I would be fine to drop the path setting.

Dan Doyle
GlobalNOC Software Developer
1-812-856-3892
daldoyle@globalnoc.iu.edu

**Comment by arlake228** [comment]
There is no downside to having that configurable. You aren't requiring anyone to configure it, but doesn't handcuff someone if they are in an environment that has a different path. For example, if I want to try a newer version of iperf3 as a developer on a system that already has the standard version, i could stick it someplace else and still test it with pscheduler. Alternatively, if I am trying pscheduler and iperf in an OS that ends-up sticking the tool someplace else, I have an easy option to change that path.  I expect 99% of the time no one will touch the option, but that doesn't mean we shouldn't have it available. You don't want to require an entire new tool just because of a simple path difference. That's closer to the sins of BWCTL than making the path configurable.

**Comment by mfeit-internet2** [comment]
I'd still prefer separate plugins because betas can be fielded and tested on production hosts with a very low preference value without interfering with regular operations.

But this is a config value just for `pscheduler-tool-iperf3`, so I guess there's no reason not to pull it.

**Pull request merged**
