### PR TITLE
pscheduler-tool-twping: use reverse flag instead of flip

### PR DESCRIPTION
**Pull request by vvidic**
Reports latency from destination to source.

### CODE REVIEW

**Comment by vvidic** [comment]
Replaces the incorrectly used flip flag in twping tool.

**Comment by vvidic** [comment]
Also do we need to switch src and dest in the test results somehow when this flag is set?

**Comment by vvidic** [comment]
Here is what the test result looks like:

```
{
  "schedule": {
    "duration": "PT21S",
    "start": "2018-03-13T16:12:54+01:00"
  },
  "tool": {
    "version": "1.0",
    "name": "twping"
  },
  "participants": [
    "jessie-amd64"
  ],
  "result": {
    "max-clock-error": 20.27,
    "packets-duplicated": 0,
    "succeeded": true,
    "histogram-latency": {
      "142.49": 3,
      "142.53": 10,
      "142.38": 1,
      "142.39": 3,
      "142.31": 2,
      "142.54": 5,
      "142.51": 9,
      "142.30": 1,
      "142.48": 9,
      "142.43": 1,
      "142.35": 1,
      "142.36": 2,
      "142.41": 2,
      "142.52": 8,
      "142.40": 1,
      "142.50": 18,
      "142.42": 1,
      "142.45": 5,
      "142.44": 3,
      "142.47": 11,
      "142.46": 4
    },
    "histogram-ttl": {
      "255": 100
    },
    "packets-sent": 100,
    "packets-reordered": 0,
    "packets-lost": 0,
    "packets-received": 100,
    "schema": 1
  },
  "test": {
    "type": "latency",
    "spec": {
      "dest": "192.168.122.100",
      "reverse": true,
      "schema": 1
    }
  },
  "id": "355ed784-949f-47e2-b661-f9afb9f303ec"
}
```
So maybe the ``"reverse": true`` could be used as an indication this is from dest to source?

**Comment by mfeit-internet2** [comment]
Having the `reverse` in there should be enough of a clue that the test was done in the reverse direction.  No need to change anything else.

The commit looks fine; will merge if nobody has anything else to say about it.

**Comment by mfeit-internet2** [comment]
Rats.  It just dawned on me that we need to bump the schema version and deal with that in several other places.  I'll write a ticket on that.

**Pull request merged**
