### PR TITLE
Set RLIMIT_NOFILE and RLIMIT_NPROC in init and service files.  toolkit#293

### PR DESCRIPTION
**Pull request by vvidic**

### CODE REVIEW

**Comment by arlake228** [comment]
This looks good to me. @mfeit-internet2 are you okay with it?

**Comment by mfeit-internet2** [comment]
I should be okay with it in theory, but @daldoyle is still bumping the ceiling on the I2 PAS machines.  That's being looked at as we speak.

**Comment by tonin** [comment]
@mfeit-internet2 It might be worth trying this patch to see it is any better at solving this issue as @vvidic had found that the current `perfsonar.limit` file might not take effect on serviced services.

@daldoyle Are you able to test this?

**Comment by mfeit-internet2** [comment]
What we observed on the I2 PAS machines was that some of the daemon processes were using enough futexes that they'd hit the 64K-per-process limit on locked memory and experienced failures.  Dan bumped that limit to 256K, is still having a few problems and is going to try 512K.  My inclination is to go high or make it unlimited.

**Pull request merged**
